@extends('layouts.app')

@section('content')
    <h2 class="font-logo text-semibold text-center text-xl sm:text-left sm:text-2xl">
        Privacy Policy
    </h2>

    <div class="text-xs">
        <p class="mb-2">
            This website uses Analytics to help Analyse how users use the site. Our Analytics software uses "cookies,"
            which are tiny text files placed on your computer, to collect standard Internet log information and visitor
            behavior information in an anonymous form. The information generated by the cookie about your use of the
            website (including your IP address) is then transmitted to our Analytic Software. This information is then
            used to evaluate visitors use of the website and to compile statistical reports on website activity.
        </p>
        <p class="mb-2">
            We will never (and will not allow any third party to) use our Analytical Software to track and/or to collect
            any Personally Identifiable Information (PII) of visitors to our site. We will not associate your IP address
            with any other data information. We will not link, or seek to link, an IP address with the identity of a
            computer user. We will not associate any data gathered from this site with any Personally Identifiable
            Information from any source, unless you explicitly submit that information via a fill-in form on our
            website.
        </p>
        <p class="mb-2">
            You may choose to accept or decline cookies. Most Web browsers automatically default to accept them, but you
            can modify your browser setting to decline cookies. If you reject cookies by changing your browser settings
            then be aware that this may disable some of the functionality on our Website.
        </p>
        <p class="mb-2">
            We will not sell, pass on, give away, or in any other format transmit your personal information. Any
            information submitted to us is sent to Burgess Repair Services ONLY.
        </p>
        <p class="font-semibold mb-2">
            3rd Party Policies
        </p>
        <p>
            Related services and offerings linked to or from this website have their own privacy statements that can be
            viewed by clicking on the corresponding links within each respective website. Since we do not have control
            over the policies or practices of participating merchants and other third parties, we are not responsible
            for the privacy practices or contents of those sites. We recommend you review their policies before you
            provide any personal information or complete any transaction with them.
        </p>
    </div>
@endsection
